export const ADD_BOARD_ACTION = "ADD_BOARD_ACTION";

export const SELECT_BOARD_ACTION = "SELECT_BOARD_ACTION";

export const ADD_NEW_TASK_ACTION = "ADD_NEW_TASK_ACTION";

export const CHECK_SUBTASK_ACTION = "CHECK_SUBTASK_ACTION";

export const ADD_NEW_COLUMN_ACTION = "ADD_NEW_COLUMN_ACTION";
